# Generated by Django 5.2.8 on 2025-12-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('SME', 'SME'), ('GIFTING', 'Gifting'), ('CORPORATE', 'Corporate')], default='SME', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_id', models.CharField(blank=True, max_length=50)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.network')),
            ],
        ),
    ]
